### ISSUE TITLE
Grid last row misaligned when using flexible width with item-layout count

### ISSUE THREAD

**Issue by Mushymato** [focustense/StardewUI#20]
When using a grid with `item-layout="count: 6"` with non-fixed width layout, the final row is misaligned

```
<grid layout="64px content" item-layout="count: 6" horizontal-item-alignment="middle">
    <image *repeat={AllCrops} sprite={Seed} focusable="true" click=|^SelectThisCrop(this)| layout="64px 64px" />
</grid>
```

![image](https://github.com/user-attachments/assets/9fb008ef-f7fa-45fe-9e28-146696765ee6)

**Comment by focustense** [comment]
This might be partly because 64px is simply a nonsensical width for the entire grid (it's intended to be the item/column width, but specified here as the whole grid width). I'll have to check to see if the same issue occurs with a grid that's correctly horizontally sized.

Either way it's definitely a bug in the grid layout.
