### ISSUE TITLE
TooltipData fails on duck typed converter

### ISSUE THREAD

**Issue by Mushymato** [focustense/StardewUI#65]
The new duck type converters generally works, but not on TooltipData where it errors.

Log: https://smapi.io/log/8c5a2abde8f64c3799002825544a7f98
Repro mod: [DuckTooltip.zip](https://github.com/user-attachments/files/17943214/DuckTooltip.zip)

**Comment by focustense** [comment]
I'm looking into it now. It's easy to repro in a unit test. The log in this case doesn't actually help because there is no log output associated with a converter that _isn't_ created, and I was reluctant to add it to to the `DuckTypeConverterFactory` because it could be spammed constantly. But I think some trace output with `LogOnce` might provide the right level of detail.

**Comment by focustense** [comment]
Root cause turned out to be pretty ridiculous, I just forgot to add `[DuckType]` to the `TooltipData`.

Took the opportunity to add tracing in case this happens with other types that are supposed to work.
