### ISSUE TITLE
Text wrapping for languages without space between words. 

### ISSUE THREAD

**Issue by Mushymato** [focustense/StardewUI#73]
Some languages don't have a space character between words and that breaks text wrapping.

Affected languages: chinese, japanese, korean 
Likely affect custom languages like Thai as well. 

![image (1)](https://github.com/user-attachments/assets/87c5adce-cc95-4abe-a246-5b47a8f50a11)

**Comment by focustense** [comment]
Since this is theoretically an issue in all languages - German, even English could have a single word that's too long for one line - there should be a fallback to character breaking when that happens.

Normally this involves hyphenation, but I have a suspicion that CJK shouldn't hyphenate, just break. Is that correct?

**Comment by Mushymato** [comment]
Yes CJK should not hyphenate.
